### ISSUE TITLE
Update site structure

### ISSUE THREAD

**Issue by katrin-k** [rails-girls-summer-of-code/summer-of-code-2014#141]
I'd suggest to change minor structure aspects and align the website's and the teams app's header (=have it the same on both sites). But since getting the website updated is most pressing now, I suppose it's best to dicuss the site's structure, where all the content goes, what content will be shown where, etc. 
Here's the gist as a kickoff: https://gist.github.com/katrin-k/cf28eebc772faa3a4790

Below's a mockup for the home page of the website. Definitely stuff missing, but couldn't help fiddling around… ¯_(ツ)_/¯ 

![draft rgsoc home page desktop](https://f.cloud.github.com/assets/2246045/2237539/2a66b3a8-9bb0-11e3-9148-8eac96d860b8.png)

![draft rgsoc home page mobile](https://f.cloud.github.com/assets/2246045/2237538/2a53ffec-9bb0-11e3-8688-c0a47db5543e.png)

**Comment by lislis** [comment]
+1
Edit: 
Maybe we could make the Last year's teams section with image tiles and a nice hover effect :)

**Comment by svenfuchs** [comment]
@katrin-k the site structure you've gisted looks good to me, although this usually needs to grow as we go.

I'd like to keep the header menu on the main site and the teams app separate, at least for now, since we need some flexibility when adding featues to the teams app. I think the current solution there isn't too bad.
