### ISSUE TITLE
Rework the campaign/donations page

### ISSUE THREAD

**Issue by svenfuchs** [rails-girls-summer-of-code/summer-of-code-2014#142]
http://railsgirlssummerofcode.org/campaign could use some design love and copy needs to be changed so it works as long as we don't have too many donations (we'll need to change it a couple times while the campaign is running)

**Comment by svenfuchs** [comment]
@anikalindtner did you mean to close this?

**Comment by sareg0** [comment]
Okay. I have been brainstorming

## 

Tagline Options:
More women in tech means = a better tech industry

Getting more women into open source, one Summer at a time.

Open Source <3 Diversity

Diversity = better Open Source

Copy:

In 2013 we changed the lives of over 30 students from all over the world, by giving them the chance to work on Open Source. This year we want to do better.

In 2013, the gender ratio of women to mean in the tech industry is ___. Of those figures women make up less that __% of contributors to Open Source.

By providing a stipendium of __ per person/month for three months (July-September), RGSoC helps students dedicate all of their efforts to learning to contribute to Open Source and push themselves to the limits of their abilities as newcomers to programming. 

Unlike several other Summer of Code programs, we don't require participants to have a degree or anything other than a basic knowledge of Ruby. Why? Because most of our applicants are newcomers, career changers, and Rails Girls Alumni, male and female.

Not only does this get more women and beginner's into open source, it also creates a bigger corps of Open Source contributors, making Open Source more accessible and representative of 100% of the population! That's the Open Source we want to see.

Get involved! Donate what you can via the form below, or let us know if you can coach, mentor or even sponsor a package. Organizing a conference? Let us know if you have some spare tickets or spare speaking slots. Have some spare workspace and developers? Let us know if you'd like to be a coaching company.

Because more diversity in Open Source means a better industry for everyone.

## 

Taglines are good... They can explain to you why should donate in a sentence, and or communicate the core concept quickly

Main Copy: feel free to muck around with this, I am just experimenting. Could be a bit long currently, and pully on the heartstrings... Either way, happy to have everyone tighten it up.

Enjoy, comment.

**Comment by sareg0** [comment]
Here is a nice selection of 'things you should consider' with your donation landing page.
