### ISSUE TITLE
Rework Design

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code-2014#176]
Would be awesome to have somebody to look over the whole design/concept again and spot weird things and maybe give a fresh look.

**Comment by anikalindtner** [comment]
maybe the super power designers @saltinejustine and @ngkhanhlinh?

**Comment by ngkhanhlinh** [comment]
Sure thing, @anikalindtner! I think it's time to give the design concept a fresher look. @saltinejustine — would you have time to join us?

**Comment by sareg0** [comment]
yay!!! The campaign page needs some real love. A beautiful fun drawing would be great to create a lovely landing page!

**Comment by anikalindtner** [comment]
@ngkhanhlinh so great to hear! <3 i'm so looking forward to your ideas!

**Comment by ngkhanhlinh** [comment]
Hey guys, I'm working on the new design concept now. Just wondering if we have Rails Girls SoC & Rails Girls photos available somewhere that we can use? @anikalindtner @svenfuchs?

**Comment by svenfuchs** [comment]
Hey @ngkhanhlinh great to hear you're back :)

I don't know about any central resource, but there are plenty of images on Flickr. I guess normally that shouldn't be an issue to use these. Also, we can always contact people to ask for allowance, should we decide we want to use a specific photo.

Before you put tons of work into drafts, would you mind sharing your ideas about concepts for the new design?

**Comment by ngkhanhlinh** [comment]
Hey @svenfuchs — thanks for this! I just searched for Rails Girls on Flickr and there are quite many photos. I'll see if we need to ask for permission from any of these. Let me know if you know any other sources. :) 

I'm working on a new concept that integrates the header image & the header banner since IMO it takes quite long to scroll down until you reach the content. Apart from this, I really like the content structure of the landing page, so I'm not planning to make any changes there. But, as always, let me know if you notice any elements that need a redesign. That would be super helpful. :)

**Comment by svenfuchs** [comment]
@ngkhanhlinh I think the current front page actually is the one page that works best on our site atm :) But of course I'm super curious to see your ideas about it.

I guess the overall look has somewhat improved when we re-structured and cleaned up the content section, adding the content menues to the right sidebar etc. I think at that point I've also changed the content and headings font. We've had no less than 3 different sanserif fonts used on the page :)

What I'd like to see would be some more attention to details, and refinements on things such as the TOC bullet point lists, e.g. on http://railsgirlssummerofcode.org/about/roles, the contents menu section on the sidebar. Also, the blog could use some touches, I guess: http://railsgirlssummerofcode.org/blog/2014-05-07-meet-the-first-seven-teams-rgsoc-2014

Also, I'd love to hear your thoughts about the campaign page, even if improvements might be a little late to that page, we could re-use the design next year: http://railsgirlssummerofcode.org/campaign The look certainly isn't that bad, but something about the page feels boring and oldschool to me.

So, I guess, what I'd think is most relevant at this point is refining what we have to an overall more consistent, and more polished, more modern look, if that makes sense :)

**Comment by ngkhanhlinh** [comment]
Thanks for your feedbacks @svenfuchs! Great to have your opinion on this, and glad to know that the front page is the one that works best on the site!

I'm working on the items you suggested for now, and after we're done with the design for these items, I'll go back to the front page. It's working well but it's still possible to optimize it—we'll see. :)

**Comment by svenfuchs** [comment]
awesome, thanks @ngkhanhlinh! looking forward to seeing your gorgeous drafts :)

**Comment by ngkhanhlinh** [comment]
At long last, here are some first drafts for the blog, the campaign page and the TOC. Not sure if I'm going in the right direction, so your inputs are needed @svenfuchs @anikalindtner! :)

**1. Blog Concept.** Mainly fixed the right sidebar so that all the subscribing features and social icons are in the same place now. I also made minor changes to the headline and the author-date subheadline, but nothing drastic. 

![blog-concept-1](https://cloud.githubusercontent.com/assets/4908043/3077892/72101b36-e449-11e3-9aca-57181ae5b0c0.jpg)

**2. Campaign Concept.**
- Concept 2.1: With catchy header and typography changes, no page structure changes. I really like this look even though there's a lot of information on the same page. 

![campaign-page-concept-1](https://cloud.githubusercontent.com/assets/4908043/3077905/490d1abc-e44a-11e3-8538-f75d2b3f60bb.jpg)
- Concept 2.2: This concept is more straightforward and structured since I divided the page into 3 main tabs, but IMO it's better to see all the donors to the campaign directly rather than having to click through to the tab. 

![campaign-page-concept-2](https://cloud.githubusercontent.com/assets/4908043/3077916/ac23e702-e44a-11e3-8461-5988d3b6005b.jpg)

**3. TOC Concept.** I removed the stars and made minor typography changes, but nothing drastic, again. This is because I felt adding too many stars made the TOC feels cluttered, but that's my only concern with it. Feel free to disagree though if you feel we need to go in totally different directions.

![toc-concept](https://cloud.githubusercontent.com/assets/4908043/3077925/19a3ad76-e44b-11e3-82db-422f09395492.jpg)

Keep in mind these are first drafts so there are plenty of opportunities for fine-tuning, or even switching to a different concept. Any thoughts, comments, suggestions? :)

**Comment by svenfuchs** [comment]
@ngkhanhlinh awesome stuff!

#### Blog concept

:+1: let's just implement that. I think the (currently empty) "Team Blogs" section in the sidebar should probably be preserved but hidden for now. We'll have links to team blog posts there as soon as they show up in our teams app (which aggregates blog posts from teams from their own, external blogs).

#### Campaign concept

I agree 2.1 is better. On a page like this, even if there's a lot content, we don't want to hide things behind tabs. I believe in a case like this it is actually a good thing to have a lot content ... it looks impressive, even though people won't read all of it.

Some thoughts:

I really like the header. Maybe we could just implement it? And keep the rest of the page the same for now until we know how to change things more?

Not sure about moving to donations button next to the status bar. Hmmm, depends how this would work next year, when it would start out with an (almost) empty status bar.

How about changing the horizontal bars to something like the squiggly line on the homepage? Or maybe use a star here with two short horizontal lines left/right to it?

I'd love to see some ideas re how to make the status bar and the sponsors boxes/buttons less clunky.

#### TOC concept

Looks great! Let's implement that.

The TOC on the page itself could use some love, too. Could we just use the same/similar styles there? Like, removing the bullet points and nesting? Not sure if we have any TOCs that nest more than one level deep.

**Comment by ngkhanhlinh** [comment]
Thanks, Sven! 

**1. Blog Concept.** I created the blog design with the team blogs in mind, to ensure we have plenty of space for this. When are the team blogs scheduled to be live? I can add a temporary mockup in the meantime. 

**2. Campaign Concept.** Great feedbacks! I'll give the status bar and the sponsor boxes some thoughts. There are definitely ways to make them less clunky, but I'm just trying to keep the status bar since I really like the dribble. ;)

**3. TOC Concept** I think we can definitely remove the bullet points and nesting. Gonna create a quick mockup for this too, so we can see how it looks. 

Going to post new mockups tomorrow based on your feedbacks. :)

**Comment by svenfuchs** [comment]
@ngkhanhlinh awesome, looking forward to that :)

**Comment by ngkhanhlinh** [comment]
Here are the new mockups. :)

**1. TOC Concept.** I removed the bullet points and one level of nesting. 

![toc-concept-version-2](https://cloud.githubusercontent.com/assets/4908043/3141903/c3c4175c-e99e-11e3-9f83-5d1d93813dd1.jpg)

**2. Blog Concept.** Added the team blog section (this concept includes team members' names in addition to team names.) 

![blog-concept-3](https://cloud.githubusercontent.com/assets/4908043/3141917/85b27f7a-e99f-11e3-8006-c5180b2c70be.jpg)

**3. Campaign Page Concept.** Added a new progress bar, removed the box in the sponsors section, and stylized the horizontal lines, changed headline typography for consistency with the rest of the site. 

![campaign-page-concept-6](https://cloud.githubusercontent.com/assets/4908043/3141949/f1ac410a-e9a1-11e3-9637-f77387b9f82d.jpg)

Again, any feedbacks are appreciated! :)

**Comment by FloorD** [comment]
My 2 cents.
First off: I love the improvements. Love. Them. More specifically on the 3 screens:
1. TOC Concept. 
   I’m happy that the many stars are gone from the ‘sidebar’ and that you solved the crazy unordered lists and their indentation in a smarter way.
2. Blog Concept.
   My eyes love this. Way cleaner. 
3. Campaign Page Concept.
   I like the header and everthing as off ‘Become a sponsor!’
   I am not a great fan of the progress bar, however fancy and clean. I’m a fraid it looks too technical. I don’t identify with ‘7/10 teams’, I like having some sort of visual representation of those teams. It’s people! Plus: putting the contribute input field and button right next to the progress bar, looks a bit… off. You are probably optimizing space (good!), but I’d rather see it below ‘How awesome is that (…)’. Maybe accompanied by ‘you can help out as well. Yes. You!’

**Comment by svenfuchs** [comment]
I agree with @FloorD in all points.

@ngkhanhlinh could we just implement the TOC and Blog changes? Would you be able to do that?

WRT the campaign page, I really like the header, and I think we could also just go ahead with that one. 

The progress bar in my opinion would be a slight improvement, but as @FloorD said it looks somewhat technical now and the playfulness is gone. I guess that's not an easy to solve conflict (make it less clunky vs keep it playful).

I also agree that the placement of the contribute button next to the progress bar seems odd. Not sure. I guess we'd want another "call to action" down there?

Also, I think the star lines don't work as well as I thought they would. What if we'd just center the headlines and add a bit more whitespace so they'd act as separators?

**Comment by lislis** [comment]
@ngkhanhlinh quick question: what font are you using in the designs? It's not the one we used so far.

**Comment by ngkhanhlinh** [comment]
@lislis I used Open Sans regular (the one on the blog side bar is 15pt), which I think is the same font, just rendered differently on Photoshop. Even if the font on the site and the mockup look a bit different, I think they look great either way. 

On the same note, is there any way to see a demo before the changes are pushed to the site? Sorry, I'm new to how Github works...

**Comment by lislis** [comment]
@ngkhanhlinh alright. I'll properly embed Open Sans then.
To see the changes beforehand you could clone my repo (https://github.com/lislis/summer-of-code.git). Did you already install a local version once? With Jekyll and all?

**Comment by sareg0** [comment]
@lislis how is this going? Have all of the redesign tasks been taken care of for the moment. I know we will have more later. Can we close this issue or is it ongoing?

**Comment by sareg0** [comment]
We're closing up this issue as we are now working on it in the above referenced repo/issue.
