### ISSUE TITLE
Clarify coaching company definition

### ISSUE THREAD

**Issue by svenfuchs** [rails-girls-summer-of-code/summer-of-code-2014#210]
On the Coaching Company guide http://railsgirlssummerofcode.org/guide/coaching-company/ we should clarify the definition of what makes a coaching company.

Something like:

A coaching company will:
- Help a team (or many teams) to thoroughly prepare their application to RgSoC. (Link to the application guide)
- Support their team working on their project during summer, should they get selected.
- Support a volunteering team working on their project during summer if possible, should their team not get selected.
- Support the remote coaches helpdesk otherwise.

Wdyt?

**Comment by carpodaster** [comment]
Ahoi!

Not entirely sure how I like that the definition of a coaching company is changed at a point were we already have a few companies willing to act as coaching company.

No 1+2 is the definition we had initially. I've never heard of 3+4 before so this should not be listed as mandatory but as an invitation.

"Voluntary team" would also need a quick definition and/or a link to it.

**Comment by berlintam** [comment]
@carpodaster I'm working on the voluntary team thing at the moment. I didn't think it was going to be important until after the selection process had been made but I can bump it up a bit.

**Comment by svenfuchs** [comment]
@carpodaster all this stuff is slightly in flux, think agile :) we need to be able to improve the system while it's already in production. 

We can be nice to companies that have signed up of course.

The reason why we need to clarify this is that coaching companies need to be able to "sign up" to this and then be accepted. I.e. this can't rely on whether their team will be selected or not. Thus, there needs to be an alternative branch for what happens when the team hasn't been selected ... and they can still act as a coaching company by that definition.

**Comment by carpodaster** [comment]
Isn't it more the process of becoming a coaching company that needs clarification instead of what a CC is? The way I understood it: You are a Coaching Company the moment your team gets selected. Period. I think we make it sufficiently clear that you can't expect your students to be chosen just because you're a company backing them.

**Comment by katrin-k** [comment]
Indeed. we can't just put a different requirement out there without thinking of who'll be affected by it and communicate this. buuut, the clarification is necessary nonetheless. (this discussion clearly shows it ;).) 

Because: CCs are not just coaches that have a team and have their coworkers help as well. CCs are companies that support by RGSoC by hosting and coaching a team (funded or volunteer). 3+4 are alternatives in case the teams doesn't get selected. 

@carpodaster it might've worked that way in your case and that's fine. Also, don't worry, we won't just put this as a requirement on Absolventa since you obviously communicated it in a different way to your coworkers. However, it'd be great if Absolventa, ie. you and your fellow devs can still regularly support RGSoC even if "your" team is not chosen. 

Soooo. this is another shot. (thumbs up-horizontal-down, plz)

#### What CCs do

In essence, you give away a piece of space in your office for your team to work in, and make sure that team have access to developers to coach them. You host and coach a team. Please read about "Being A Coach" to know what coaching includes. Hence, a Coaching Company provides the basic infrastructure for a team. 

A coaching company will:
- Support a team (or a few teams) to thoroughly prepare their application to RgSoC. (If you already have a team, that is) {Link to the application guide}
- Coach the hosted team during their project, should they get selected. (Read more on "Being A Coach") {Link to coach guide}

In case the supported team(s) don't get selected for a scholarship, alternatively you can:
- Support a volunteering team working on their project during summer. {Link to volunteering teams def, when ready}
- Support the remote coaches helpdesk otherwise.

All of the extras are up to you. You might want your team to present their work at weekly team meetings, so the whole company can stay up-to-date on their progress, or you can support them to attend conferences and meetups by taking them along.
