### ISSUE TITLE
Collecting job postings / internship requests 

### ISSUE THREAD

**Issue by FloorD** [rails-girls-summer-of-code/summer-of-code-2014#247]
In the comments of this issue we will be collecting inquiries from companies looking to hire junior developers / interns straight out of the Rails Girls Summer of Code program - following [Tam's blog post](http://railsgirlssummerofcode.org/blog/rgsoc-internships/).

**Comment by FloorD** [comment]
ben@projectj.co
22-08-2014

Hi!

I saw your blog post about Internships and would be really interested in offering an intern position at our startup, which is based in London and Berlin.
http://railsgirlssummerofcode.org/blog/rgsoc-internships/

Project J is an early stage startup that is reimagining eCommerce for women's accessories. Culturally, we're creating a working environment where people can really grow and develop together. We are hoping to find candidates that match our ambitions in both domains and help grow our ideas / ideals into an organisation that the larger developer community will hold up as an example of a great technology company. We're just closing our first round of funding, so this is a great time to join.

Outside of my role as Lead Developer at Project J, I am a programming tutor at codebar.io  in London (a Rails school for underrepresented groups in tech). I have helped many people get to the next level in their careers and I take great pride in being the best mentor I can be.

Cheers,

Ben

**Comment by anikalindtner** [comment]
Hi,

I'm emailing to volunteer ourselves as a willing and keen employee of an intern following this summer's Summer of Code. I have to be honest and say that we are a London company, and acknowledge that you aren't looking here as a primary area, however we would be delighted to hear from people who are allowed to work in the EU.

I helped with Rails Girls London last year, and personally and as a company would be delighted to help the movement and those participating in any way that I or we can.

Kind regards,

John Maxwell
Lead Developer

Board Intelligence
Tel: +442071928200
Mob: +447453320745
John.Maxwell@boardintelligence.co.uk

**Comment by anikalindtner** [comment]
Hi there,

Pospulse/Etventure ist looking for a development intern with Ruby on Rails skills for 3-6 months in the Berlin office, with the option of transferring to a regular job after the (paid) internship. Could you spread the attached job offer through your channels?

Thank you!

Rebecca

## 

POSpulse
Büro Ackerhöfe
Ackerstr. 14-15
10115 Berlin
Germany

rebecca.cotton@pospulse.com
+49 (0) 30 7492 7826

www.pospulse.com

![screen shot 2014-08-23 at 14 26 42](https://cloud.githubusercontent.com/assets/1711357/4020578/cd4ce610-2ac0-11e4-81c2-c7615ccc4cda.png)
![screen shot 2014-08-23 at 14 26 47](https://cloud.githubusercontent.com/assets/1711357/4020579/d0339f04-2ac0-11e4-9489-25a7c7dbd1c3.png)
![screen shot 2014-08-23 at 14 26 53](https://cloud.githubusercontent.com/assets/1711357/4020580/d6b3a87e-2ac0-11e4-886a-533af0c84f51.png)

**Comment by sareg0** [comment]
We have decided that these are probably best stored in the teams app. That way they are not public, but can be viewed with their essential info instead of having to scroll through all of them here. 

Didn't we have more than this? I can look through my mails, but just in case anyone knows of the top of their head about further offers of internships, please put them in here. 

@carpodaster what do you think about getting these job postings into a table in the teams app. Much like the conferences page (http://teams.railsgirlssummerofcode.org/conferences)

**Comment by alicetragedy** [comment]
edit to @sareg0's comment above: of course, unlike the conferences page, it would be for signed in users only and maybe we can even narrow it down to admins+orgas+students.. (haven't looked much at the code of the teams app, so I am not sure about the authorization levels)

that's quite important since we would probably have contact information we don't want to share with everyone... (:

**Comment by carpodaster** [comment]
@sareg0 @alicetragedy Sure, can do. Maybe even tonight. If you're on the supervisors' call tonight, we can talk about it after it?

**Comment by sareg0** [comment]
Yup I'll be on the call.

**Comment by sareg0** [comment]
@alicetragedy good point. I forgot to mention that.

**Comment by carpodaster** [comment]
@sareg0 http://teams.railsgirlssummerofcode.org/job_offers/

**Comment by sareg0** [comment]
I have emailed the two top offers, just for a little extra detail. I was going to close this issue up, and simply input the job offers into the area on the teams app. Anyone else on the organizers team can do the same.
