### ISSUE TITLE
gh-pages branch as the default?

### ISSUE THREAD

**Issue by PragTob** [rails-girls-summer-of-code/summer-of-code-2014#8]
There isn't much to be seen in the master branch as of now, so why not make the gh-pages branch the default branch? :-)

**Comment by lislis** [comment]
Good idea. But we have to keep the gh-pages branch because that's basically the webroot for a github pages website.
So, is it possible to make the master branch adopt to the gh-pages?

**Comment by svenfuchs** [comment]
@lislis i believe @PragTob meant to make the `gh-pages` branch the default branch for this repo on github, so it's show it on the frontpage of the repo.

I just noticed that in order to do so you need admin access on the repo and the collaborators team doesn't have it. So I've just went ahead and changed it:

![image](https://f.cloud.github.com/assets/2208/419386/c4ba610e-accb-11e2-80d5-4640227786f5.png)

**Comment by lislis** [comment]
Oh perfect :D

**Comment by PragTob** [comment]
Awesome :-)
