### ISSUE TITLE
Design changes

### ISSUE THREAD

**Issue by lislis** [rails-girls-summer-of-code/summer-of-code-2014#84]
Hey everyone! I thought about possibilities to give the main website a little makeover.
This is totally up for discussion, so comment!

(And sorry for the sloppy Photoshop work)

---

![students](https://f.cloud.github.com/assets/1006478/715890/75095526-df29-11e2-8162-d376d52f27c0.png)

Students page

---

![blog](https://f.cloud.github.com/assets/1006478/715896/989c0768-df29-11e2-9bd9-1cb0bd6f1f85.png)

possible blog page
Someone mentioned that there is a newsletter now. I would put it underneath the RSS (or maybe the other way around?) And would it be a link or a direct input or something?

---

![about](https://f.cloud.github.com/assets/1006478/715907/f6d017ac-df29-11e2-8972-b3415036ece5.png)

Possible About/ Contact page. (Yes, activities is a croped screenshot ;))

**Comment by svenfuchs** [comment]
Nice ideas!

On the About page it might make sense to have various contact opportunities listed in the sidebar, rather than activities?

**Comment by lislis** [comment]
yes, you're right. Makes definitely sense.
So a link to Twitter, GH, the mailinglists and to the normal e-mail adress. and then a scribble :D

**Comment by anikalindtner** [comment]
hej @lislis we got some new scribbles (whohoo!) i'll add these here. if you want me to open new issues for every page, so that we can close one at a time, just tell me and i'll do it :)

blog:
![megaphon](https://f.cloud.github.com/assets/1711357/749150/b7bf9a52-e4a0-11e2-8da1-cb3a637e8d85.png)

for the tools page:
![scribbles_werkeug](https://f.cloud.github.com/assets/1711357/749164/5790ddca-e4a1-11e2-9415-d70124479a4c.png)

here you'd have to separate the pics - i just left them in one png, but i think in order to use them for the page we might use them one after on? 
![scribbles_werkeug_schrauben](https://f.cloud.github.com/assets/1711357/749171/a0e8d6a8-e4a1-11e2-8c57-5b8e90081431.png)

for the students page:

same as for the tools, you would need to separate the pics, you want to use:

(if you need help with that, just let me know)
![scribbles_buecher2](https://f.cloud.github.com/assets/1711357/749188/2b9a9c82-e4a2-11e2-97d8-b44f076286c1.png)

**Comment by lislis** [comment]
Yes, add some issues please :)
I'll get around that asap

Am 04.07.13 14:06, schrieb Anika:

> hej @lislis https://github.com/lislis we got some new scribbles 
> (whohoo!) i'll add these here. if you want me to open new issues for 
> every page, so that we can close one at a time, just tell me and i'll 
> do it :)
> 
> blog:
> megaphon 
> https://f.cloud.github.com/assets/1711357/749150/b7bf9a52-e4a0-11e2-8da1-cb3a637e8d85.png
> 
> for the tools page:
> scribbles_werkeug 
> https://f.cloud.github.com/assets/1711357/749164/5790ddca-e4a1-11e2-9415-d70124479a4c.png
> 
> here you'd have to separate the pics - i just left them in one png, 
> but i think in order to use them for the page we might use them one 
> after on?
> scribbles_werkeug_schrauben 
> https://f.cloud.github.com/assets/1711357/749171/a0e8d6a8-e4a1-11e2-8c57-5b8e90081431.png
> 
> for the students page:
> 
> same as for the tools, you would need to separate the pics, you want 
> to use:
> 
> (if you need help with that, just let me know)
> scribbles_buecher2 
> https://f.cloud.github.com/assets/1711357/749188/2b9a9c82-e4a2-11e2-97d8-b44f076286c1.png
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/rails-girls-summer-of-code/summer-of-code/issues/84#issuecomment-20473728.

## 

Lisa Passing

+49 (0) 176 613 276 35
passinglisa@gmail.com

**Comment by lislis** [comment]
new scribbles added, commit:  fea8dee397b7da8f118444c98a65eb75a8f88828

**Comment by anikalindtner** [comment]
hej @lislis could you put the megaphone on top of the blog-sidebar? i think this would look even better :)

**Comment by lislis** [comment]
sure :) Commit: 3b0b31c55fd061b43cde917a1de8bbe89e00df6f
