### ISSUE TITLE
New front page

### ISSUE THREAD

**Issue by lislis** [rails-girls-summer-of-code/summer-of-code-2014#85]
What do we want to display on the Homepage?
Possibilities:
- some sort of introduction
- the video
- twitter feed
- team activity feed
- recent blog posts
- ...

And how do we want to presend it? I think it's hard to further work with the parallax / scrolling effect, it dominates the page too much and predetermines the layout. Maybe go with a smaller slideshow? Or mybe we could put those awesome scribbles into the center of attention?

**Comment by ngkhanhlinh** [comment]
Hi Lisa, 

Nice ideas! I also think that the parallax effects is limiting the layout too much, and the scrolling effect was not as smooth (perhaps due to the slow loading time?) 

I've thought about two ideas for the homepage. First, perhaps we can streamline the website to match the brand identity of the Rail Girls website: http://railsgirls.com/. This homepage places a stronger focus on the video and the lovely scribbles. We can replace the Upcoming Events sidebar with activity feed or recent blog posts? 

Another option is to go with a smaller slideshow using those awesome photos of Rail Girls on the current homepage. I love this option too, although personally I think the first option add more uniqueness to the website thanks to our scribbles.

I can put together a mock-up this week once we have a clearer picture. So, please let me know your thoughts! :)

**Comment by lislis** [comment]
Hey Linh,

matching the Summer of Code style to the original Rails Girls site is a good idea. And it would be very cool if you could do some mock-ups. I think working on something is easier if you have a clear picture/ guideline in front of you :)

**Comment by ngkhanhlinh** [comment]
Hey Lisa and Anika,

Here are 3 mock-ups with my ideas on how we can re-design the front page. Can you take a look and let me know what you think? These are simply first drafts so there is lots of room for improvement. I can do some other mock-ups if we come up with other ideas! 

**Version 1 - Focusing on image, videos and dribbles. We can add more images to make a slide-show.**

![mockup-1](https://f.cloud.github.com/assets/4908043/793550/503f28d8-ec17-11e2-9375-f50333fed44b.jpg)

**Version 2 - Focusing on images and dribbles.**

![mockup-2](https://f.cloud.github.com/assets/4908043/793551/da00e96c-ec17-11e2-87be-d57614bf0ddd.jpg)

**Version 3 - Simple version based on Rails Girls website with no images.**

![mockup-4](https://f.cloud.github.com/assets/4908043/793572/dd1be96a-ec19-11e2-9c5d-76826d4fab2e.jpg)

And yes, the sponsors were simply taken from the current SoC site. I also took the idea for the navigation from your suggestions on Github. The right sidebar on the right is also up for discussion: should we include the team blogs, team activities or the twitter feed? 

I'm staying open to any feedbacks or comments. Love Rails Girls SoC <3

**Comment by carlad** [comment]
Nice work. I quite like the second one...

**Comment by bioshrimp** [comment]
^^ me too. :)

**Comment by lislis** [comment]
Thanks for the designs!! I would also root for number 2 :D 
@anikalindtner do the teams (or some of them) have their own logos or pictures? We could implement those on the sidebar.
And instead of projects wanted the latest blogs post, or the headlines of the last 5 posts or so.
What do you think?

**Comment by ngkhanhlinh** [comment]
Thank you all for your comments! Number 2 was my personal favorite too :-) 

@lislis I think adding the recent blog posts is a really good idea! If we go with option 2, I can also add a "Donate Now!" button under the illustrated banner.

**Comment by lislis** [comment]
Sure! Would be really cool :)

**Comment by anikalindtner** [comment]
hejhej! i think version 2 is a very cool design! but i would just put the blog there, not the "projects wanted" and the "women go open source" at the bottom. do you know, what i mean?
@lislis no, the teams have no official picture, but i do have team pictures from almost all of them (see: http://railsgirlssummerofcode.org/blog/the-beginning/)

and i don't think we need the "donate now" button so visibly anymore, since the project is already running and we are now focussing more on keeping everybody up-to-date with the teams and so on... what do you think?

**Comment by anikalindtner** [comment]
oh and! nice job, this really looks awesome!

**Comment by svenfuchs** [comment]
Amazing work! 

I like the second one best, too.

:heart: :heart: :heart:

**Comment by ngkhanhlinh** [comment]
@anikalindtner and @lislis: I think I got the idea!! I'll edit the mock-up for version 2 and upload it tomorrow. I've got really limited knowledge about HTML/CSS so I hope this frontpage is not overly complicated for coding. 

Also, I'm not really sure about adding the team photos without taking away the minimalism of the designs. How about we use them for the new teams page instead? I've got some ideas for that too. :)

@svenfuchs Thank you! The branding of Rails Girls & SoC is my favorite so it's such a joy to work with the designs. :-) :heart:

**Comment by ngkhanhlinh** [comment]
Here's the modified mock-up for version 2 (replaced **Projects Wanted!** with a recent blog post). I also added the video in the **Women go Open Source** section. Do you think I should add more blog entries or just one as a preview is enough? Any other comments or ideas are appreciated! :) 

![rails-girls-soc-demo8](https://f.cloud.github.com/assets/4908043/826321/a85b5ebe-f082-11e2-8335-3032fe31c71d.jpg)

**Comment by svenfuchs** [comment]
Hey @ngkhanhlinh 

This looks really awesome. It's called "Rails Girls" btw, not "Rail Girls" :)

May I suggest a few changes?

I'd move the section "Women go Open Source" to below the "Rails Girls" heading section (with all the nice sketches) and above the blog post / blogs section ... because this part nicely explains what Rails Girls Summer of Code is all about.

Also, please remove the buttons "Apply as a student" and "Become a sponsor" ... since we currently don't actually take applications any more.

Other than this I really love this draft and I think it should be implemented asap.

:heart: :heart: :heart:

**Comment by ngkhanhlinh** [comment]
Oh, I totally missed the typo in the "Rails Girls" heading - thank you for pointing it out! :D 

I also agree that the explanation about Rails Girls SoC should be on top, and then the blog post. What do you think @anikalindtner @lislis? :)

**Comment by anikalindtner** [comment]
hmmm, but then the users would have to scroll a long way down until they see the blog? and that's really important right now, i'd think? maybe we could replace the superbig picture of the women coding with an actual picture of our teams? linh, i can send you all team photos and maybe we can make a slimmer header aut of these?
or are these in a not good enough quality?

**Comment by svenfuchs** [comment]
@anikalindtner i think on the homepage we still need to explain what rgsoc is first, since the page is still being used as a reference (e.g. conferences recently).

**Comment by anikalindtner** [comment]
@svenfuchs yeah, i agree, that's why i thought we could make the header-image a little bit more slim, so that the users don't have to scroll down so much...?

**Comment by carlad** [comment]
Yeah the photo image at the top of the page could be trimmed, from the bottom. You just need to see the top of the womens' laptop screens (to contextualie what they're looking at.

I think a collaged picture of all the teams wouldn't look very good. The pics are all different styles, resolutions, and formats. It would look a little messy I think, and otherwise detract from what is a clean and elegant design...

**Comment by svenfuchs** [comment]
i agree with @carlad regarding a collage. but yeah, one could probably reduce the top image height a little.

let's do this somewhat iteratively though. the current draft is already much better than what we have on the homepage right now ... which people are still looking at a lot :)

@ngkhanhlinh @lislis could you implement this? and maybe move the explanation and video to the top of the blog posts section?

we can then all look at it and see how it works.

:heart:

**Comment by lislis** [comment]
@svenfuchs totally agree. I'm quite busy the next weeks but I think I can get it done in a few night shifts ;)
@ngkhanhlinh do have the design as a psd? I need the wavy border as a png and the composed scribble image

**Comment by ngkhanhlinh** [comment]
@svenfuchs @anikalindtner -- as you said, I think we should go with the original photo, but trying to make the head banner a bit shorter. I'm still trying to see what works best, so I'll send another mockup tomorrow. 
@lislis -- sure! I'll send you the original psd and the wavy border & the scribble image. Please let me know if there are anything else I can help you with! :)

**Comment by ngkhanhlinh** [comment]
@svenfuchs @anikalindtner @lislis -- here's the mockup version of the website with the top image height reduced. I've also removed the **student** and **sponsor** buttons in this version. Now we can see if we'd like to shorten the image height or keep it. What do you think? :-) 

![rails-girls-soc-demo12](https://f.cloud.github.com/assets/4908043/844667/58ebf11a-f3d7-11e2-8688-5a83d691be63.jpg)

**Comment by svenfuchs** [comment]
:+1:

this looks super awesome, @ngkhanhlinh @lislis. can't wait to see this online :)

**Comment by somamo** [comment]
The new mock up looks great. I have done some clean up to make richer in contrast. It keeps the layout more different from railsgirls.com and more self-contained.

![rg_soc_redesign](https://f.cloud.github.com/assets/3679710/849379/81e24104-f473-11e2-8c27-8dce86ab2de9.jpg)

**Comment by svenfuchs** [comment]
great work @somamo 

gotta say i like @ngkhanhlinh's version better, especially the header part. it seems more "lively" to me if that makes any sense.

I like how you've "bullet pointed" the sections using that wavey sketch.

In any case, please let's get started. All of this is much better than the current, pretty outdated page we have :)

**Comment by lislis** [comment]
i finally began working on the new frontpage, see here
Commit: 70d6eaac09cfbf5eb7fd9e3af305a7fc8bbafda8

I'll open a few issues for what needs to be done next.

@anikalindtner @ngkhanhlinh @somamo @svenfuchs and @everbody else
Check them out ;)

**Comment by svenfuchs** [comment]
Looks like this for me on a bigger screen:

![](http://s3itch.svenfuchs.com/skitched-20130725-125908.jpg)

I'm not sure how that can be solved properly, but maybe something like this would make more sense for now?

```
background: url(../img/workshop1.jpg) center 0 fixed no-repeat;
background-size: contain;
```

Also, should it have that wavey border, yet?

**Comment by svenfuchs** [comment]
great work, @lislis :)

**Comment by svenfuchs** [comment]
Oh, and shall we make the top menu bar sticky?

**Comment by lislis** [comment]
@svenfuchs  I set the background size to cover :)

I'm missing a png for the wavy border. If I find some time I can look into a svg solution, but a png would be way quicker.

About the navigation. I didn't make it transparent because there are overlapping problems with the dropdown (I don't wanna go deeper into that right now). 
Now when the color is solid, i don't like the nav to be sticky. I kind of gets on my nerves ;) what do you think?

**Comment by ngkhanhlinh** [comment]
@lislis I'm sending it to you now. I can also send another vector file if you need a bigger size. :)

**Comment by ngkhanhlinh** [comment]
@lislis I'm just wondering if we could use Interstate Bold Condensed for the **summer 2013/worldwide** element? If we make it more condensed and smaller, I think it wouldn't stand out too much. 

Also, for the general text of the website (as in blog post or introduction), I'd suggest we go for Helvetica Neue rather than Interstate since I think this font is better for long text. What do you think? :)

**Comment by lislis** [comment]
Wavy border is in there \o/
I gave the summer 2013/worldwide a normal font-weight. Currently only the normal Interstate font is embedded. I wouldn't want to embed the condensed when we would only use it once. But I think it works fine.
I also changed the default font-family to Helvetica Neue and I think you're right, this better for legibility

**Comment by ngkhanhlinh** [comment]
Yay for wavy border! :D 

Thank you @lislis -- this front page looks really good already! 

I think that if we can't embed Interstate bold condensed but use a normal font for **summer 2013/worldwide**, perhaps we could make the font size smaller? We go maybe go for 16px or 18px instead of 22px? Maybe it's just me, but I feel that this summer 2013/worldwide is standing out a bit too much? What do you think? :-)

**Comment by lislis** [comment]
I thought it was fine before but I made it 18px anyway. Looks also very nice :)

**Comment by svenfuchs** [comment]
Awesome stuff :)

I love the new homepage! :heart: :heart: :heart: 

I'd still love the top image to be positioned fixed, but I can't quickly figure out a good background positioning/size that works with various window sizes then. @lislis any chance?

@ngkhanhlinh are you comfortable doing some css here and there yourself? Shall we just add you to the repository as a collaborator?

**Comment by lislis** [comment]
@svenfuchs I have nothing offhand, but I'll make it an issue on my todo list ;)

**Comment by ngkhanhlinh** [comment]
@svenfuchs Thank you, but I'm not comfortable yet since I've just started with the basics. Hope I'll be able to contribute soon! :)

**Comment by svenfuchs** [comment]
That's fine @ngkhanhlinh! Feel free to ask for commit access whenever you feel comfortable enough :) Meanwhile, you could send pull requests, too, if you want.

**Comment by svenfuchs** [comment]
@lislis i've made a few tweaks to the top menu bar: https://github.com/rails-girls-summer-of-code/summer-of-code/commit/3ec1f7f1c1c6f8810880ae3bb929addc6500e35e

@ngkhanhlinh i kinda feel the current button style doesn't really fit the feel of the page any more. could you have a look at making that a bit smoother? (e.g. there's one button "Read more on our blog!" at the bottom, but it seems worse e.g. here: http://railsgirlssummerofcode.org/about)

**Comment by ngkhanhlinh** [comment]
@svenfuchs I believe the buttons will look smoother if we change the font to Interstate instead of Helvetica Neue. I think Interstate is always more optimal for headlines or buttons, while Helvetica is better for long text. A button with Interstate will look like this: 

![screen shot 2013-07-30 at 16 45 43](https://f.cloud.github.com/assets/4908043/878948/6fa24ebc-f91e-11e2-9468-4f390f7090b7.png)

I'll look into other button styles as well, but do let me know what you think! :-)

**Comment by anikalindtner** [comment]
hejhej, i do love stars, but i guess there are no cool star-buttons :D
btw. the page looks like this in chrome for me:
(on the right side the scribbles are cut off)

![screen shot 2013-08-06 at 12 17 30 pm](https://f.cloud.github.com/assets/1711357/916074/ab51a0d0-fe81-11e2-9c43-7d503b3da5ae.png)

**Comment by ngkhanhlinh** [comment]
@anikalindtner Good idea! I can put a cute star on the button. Wondering if it's possible to make the star appears on the button when we hovers on it?

**Comment by lislis** [comment]
@anikalindtner I think it's an resolution issue. The frontpage scribbles are one big background image and if your screen isn't big enough not everything is shown. But I'll look into it, maybe I can find a workaround.

@ngkhanhlinh  yes, totally possible :)

**Comment by ngkhanhlinh** [comment]
@lislis @anikalindtner -- Awesome! I've added the stars to the button design. Let me know what you think :-)

![screen shot 2013-08-06 at 15 31 33](https://f.cloud.github.com/assets/4908043/916663/242d45e2-fe94-11e2-8a17-785d3d33bd9d.png)

**Comment by lislis** [comment]
:+1:

**Comment by lislis** [comment]
Star buttons everywhere! 3f00585aa00c62b64f7fdc4adf3f9ca3c5979486

I would like to close this issue if nobody objects. I think I outsourced the remaining questions to other issues.

**Comment by lislis** [comment]
Close for now. It looks awesome :D
