### ISSUE TITLE
redesign and re-organize teams app

### ISSUE THREAD

**Issue by anikalindtner** [rails-girls-summer-of-code/summer-of-code-2014#92]
heyhej,

here are some ideas i collected for the teams app:
- make the user overview a little bit nicer: 
  ->give every participant a little box with infos like this:
  ![screen shot 2013-07-17 at 12 45 55 pm](https://f.cloud.github.com/assets/1711357/811249/1b60aa74-eece-11e2-947b-21b3ef818e26.png)
- include a twitterstream, that shows the latest tweets from every team
- on the team-site, rank the teams by activity, so that the team with the newest activity is first
- make the date in "latest activity" a link that links to the latest blog post
- add team pictures to the team overview 

what do you think?
@lislis @ngkhanhlinh

**Comment by lislis** [comment]
Can we move this to the teams app repo? So we have the issues for the different parts in the right place?

btw, I like the icon boxes and the team pictures for the overview :D 
With the ranking we need to see what's possible programming-wise.

**Comment by ngkhanhlinh** [comment]
I really like all of the ideas above, especially the team pictures overview & the little info boxes! 

I'm just not sure about linking the date in "latest activity" to the blog post, since many teams posted their entries on the same day? If you can give an example or even just a hand-drawn illustration, it would be cool! :D

**Comment by anikalindtner** [comment]
hej, i'll move this to the teams-app! :)
